# Generated by Django 4.2.17 on 2025-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_isverified_user_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetrypiece',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
